name: google_fonts_arabic
description: Arabic fonts by google right into your flutter application.
version: 0.0.2
author: Emad O. Medher
homepage: emad@medher.info

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: Amiri
      fonts:
        - asset: fonts/Amiri/Amiri-Bold.ttf
        - asset: fonts/Amiri/Amiri-BoldItalic.ttf
        - asset: fonts/Amiri/Amiri-Italic.ttf
        - asset: fonts/Amiri/Amiri-Regular.ttf
    - family: Aref_Ruqaa
      fonts:
        - asset: fonts/Aref_Ruqaa/ArefRuqaa-Bold.ttf
        - asset: fonts/Aref_Ruqaa/ArefRuqaa-Regular.ttf
    - family: Baloo_Bhaijaan
      fonts:
        - asset: fonts/Baloo_Bhaijaan/BalooBhaijaan-Regular.ttf
    - family: Cairo
      fonts:
        - asset: fonts/Cairo/Cairo-Black.ttf
        - asset: fonts/Cairo/Cairo-Bold.ttf
        - asset: fonts/Cairo/Cairo-ExtraLight.ttf
        - asset: fonts/Cairo/Cairo-Light.ttf
        - asset: fonts/Cairo/Cairo-Regular.ttf
        - asset: fonts/Cairo/Cairo-SemiBold.ttf
    - family: Changa
      fonts:
        - asset: fonts/Changa/Changa-Bold.ttf
        - asset: fonts/Changa/Changa-ExtraBold.ttf
        - asset: fonts/Changa/Changa-ExtraLight.ttf
        - asset: fonts/Changa/Changa-Light.ttf
        - asset: fonts/Changa/Changa-Medium.ttf
        - asset: fonts/Changa/Changa-Regular.ttf
        - asset: fonts/Changa/Changa-SemiBold.ttf
    - family: El_Messiri
      fonts:
        - asset: fonts/El_Messiri/ElMessiri-Bold.ttf
        - asset: fonts/El_Messiri/ElMessiri-Medium.ttf
        - asset: fonts/El_Messiri/ElMessiri-Regular.ttf
        - asset: fonts/El_Messiri/ElMessiri-SemiBold.ttf
    - family: Harmattan
      fonts:
        - asset: fonts/Harmattan/Harmattan-Regular.ttf
    - family: Jomhuria
      fonts:
        - asset: fonts/Jomhuria/Jomhuria-Regular.ttf
    - family: Katibeh
      fonts:
        - asset: fonts/Katibeh/Katibeh-Regular.ttf
    - family: Lalezar
      fonts:
        - asset: fonts/Lalezar/Lalezar-Regular.ttf
    - family: Lateef
      fonts:
        - asset: fonts/Lateef/LateefRegOT.ttf
    - family: Lemonada
      fonts:
        - asset: fonts/Lemonada/Lemonada-Bold.ttf
        - asset: fonts/Lemonada/Lemonada-Light.ttf
        - asset: fonts/Lemonada/Lemonada-Regular.ttf
        - asset: fonts/Lemonada/Lemonada-SemiBold.ttf
    - family: Mada
      fonts:
        - asset: fonts/Mada/Mada-Black.ttf
        - asset: fonts/Mada/Mada-Bold.ttf
        - asset: fonts/Mada/Mada-ExtraLight.ttf
        - asset: fonts/Mada/Mada-Light.ttf
        - asset: fonts/Mada/Mada-Medium.ttf
        - asset: fonts/Mada/Mada-Regular.ttf
        - asset: fonts/Mada/Mada-SemiBold.ttf
    - family: Markazi_Text
      fonts:
        - asset: fonts/Markazi_Text/MarkaziText-Regular.ttf
    - family: Mirza
      fonts:
        - asset: fonts/Mirza/Mirza-Bold.ttf
        - asset: fonts/Mirza/Mirza-Medium.ttf
        - asset: fonts/Mirza/Mirza-Regular.ttf
        - asset: fonts/Mirza/Mirza-SemiBold.ttf
    - family: Rakkas
      fonts:
        - asset: fonts/Rakkas/Rakkas-Regular.ttf
    - family: Reem_Kufi
      fonts:
        - asset: fonts/Reem_Kufi/ReemKufi-Regular.ttf
    - family: Scheherazade
      fonts:
        - asset: fonts/Scheherazade/Scheherazade-Bold.ttf
        - asset: fonts/Scheherazade/Scheherazade-Regular.ttf
    - family: Tajawal
      fonts:
        - asset: fonts/Tajawal/Tajawal-Black.ttf
        - asset: fonts/Tajawal/Tajawal-Bold.ttf
        - asset: fonts/Tajawal/Tajawal-ExtraBold.ttf
        - asset: fonts/Tajawal/Tajawal-ExtraLight.ttf
        - asset: fonts/Tajawal/Tajawal-Light.ttf
        - asset: fonts/Tajawal/Tajawal-Medium.ttf

